version: '3'
services:
  fat_measurement:
    build: ./
    container_name: ct_visceral_fat_jip
    hostname: ct_visceral_fat_jip
    environment:
      - WORKFLOW_DIR=/app/workflow
      - BATCH_NAME=batch1
      - OPERATOR_IN_DIR=input
      - OPERATOR_OUT_DIR=output
      - PYTHONBUFFERED=1
    command: python3 -u /app/run_container_jip.py
    volumes:
    - ./workflow:/app/workflow
